### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by asux** [nirix/atom-editor-settings#10]
[Enter steps to reproduce below:]

1. Launch Atom.
2. Install `editor-settings` package.

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [editor-settings](https://github.com/nirix/atom-editor-settings) package, v0.5.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/asux/Яндекс.Диск/Applications/Atom/packages/editor-settings/lib/editor-settings.coffee:123

TypeError: undefined is not a function
  at Object.module.exports.setConfig (/Users/asux/Яндекс.Диск/Applications/Atom/packages/editor-settings/lib/editor-settings.coffee:123:28)
  at Object.module.exports.configureEditor (/Users/asux/Яндекс.Диск/Applications/Atom/packages/editor-settings/lib/editor-settings.coffee:105:6)
  at /Users/asux/Яндекс.Диск/Applications/Atom/packages/editor-settings/lib/editor-settings.coffee:40:10
  at /Users/asux/Яндекс.Диск/Applications/Atom/packages/editor-settings/lib/editor-settings.coffee:156:13
  at /Users/asux/Яндекс.Диск/Applications/Atom/packages/editor-settings/node_modules/season/lib/cson.js:164:53
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "deprecation-cop",
      "minimap",
      "open-in-sourcetree",
      "fancy-new-file",
      "atom-lint",
      "atom-terminal-panel",
      "file-icon-supplement",
      "file-type-icons",
      "pdf-view"
    ],
    "projectHome": "~/Projects",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-ctags, v3.2.0
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
change-case, v0.5.1
circle-ci, v0.9.1
codeship-status, v0.1.1
color-picker, v1.7.0
cucumber, v0.5.0
editor-settings, v0.5.3
file-icons, v1.5.5
file-types, v0.3.0
highlight-selected, v0.9.2
language-docker, v1.1.3
language-hosts, v0.1.1
language-slim, v0.4.0
linter, v0.12.2
linter-csslint, v0.0.12
linter-jsonlint, v0.1.3
linter-pylint, v0.2.1
linter-rubocop, v0.2.3
linter-scss-lint, v0.0.14
local-history, v3.1.0
monokai, v0.14.0
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
rspec-snippets, v0.4.0
wercker-status, v0.3.0

# Dev
No dev packages
```

**Comment by tirithen** [comment]
:+1:

**Comment by nirix** [comment]
I've performed a complete rewrite and after testing in multiple directories, and grammars, everything appears to be working.
