### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getParent' of null

### ISSUE THREAD

**Issue by bbuck** [nirix/atom-editor-settings#28]
[Enter steps to reproduce below:]

1. Open two tabs in Atom (CMD+N)
2. Switch tabs, by mouse or keyboard.

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [editor-settings](https://github.com/nirix/atom-editor-settings) package, v1.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getParent' of null

```
At /Users/bbuck/.dotfiles/atom.symlink/packages/editor-settings/lib/editor-settings.coffee:110

TypeError: Cannot read property 'getParent' of null
    at Object.module.exports.loadAllConfigFiles (/Users/bbuck/.dotfiles/atom.symlink/packages/editor-settings/lib/editor-settings.coffee:110:41)
    at Object.module.exports.reconfigureCurrentEditor (/Users/bbuck/.dotfiles/atom.symlink/packages/editor-settings/lib/editor-settings.coffee:64:17)
    at /Users/bbuck/.dotfiles/atom.symlink/packages/editor-settings/lib/editor-settings.coffee:41:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:284:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:662:19)
```

### Commands

```
     -1:16.6.0 pane:show-item-3 (atom-text-editor.editor.is-focused)
     -1:16 pane:show-item-1 (atom-text-editor.editor.mini.is-focused)
     -1:15.5.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -1:14.9.0 pane:show-item-3 (atom-text-editor.editor.is-focused)
     -1:14.5.0 pane:show-item-1 (atom-text-editor.editor.mini.is-focused)
     -1:14.4.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -1:14 pane:show-item-3 (atom-text-editor.editor.is-focused)
     -1:13.4.0 pane:show-item-2 (atom-text-editor.editor.mini.is-focused)
     -1:11.4.0 core:close (atom-text-editor.editor.is-focused)
     -1:09.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:09.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:07.9.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:50.3.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:48.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:04.3.0 application:new-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "linter-rubocop"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "node_modules",
      "vendor"
    ],
    "projectHome": "/Users/brandonbuck/Documents/Dev",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
advanced-open-file, v0.16.4 (inactive)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.3.6 (active)
atom-typescript, v10.1.7 (active)
autocomplete-go, v1.2.0 (active)
builder-go, v1.0.1 (active)
editor-settings, v1.1.1 (active)
editorconfig, v1.4.1 (active)
file-icons, v1.7.20 (active)
git-blame, v0.4.11 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
go-oracle, v0.2.1 (inactive)
go-plus, v4.3.2 (active)
godoc, v1.1.0 (active)
gofmt, v1.2.0 (active)
gometalinter-linter, v1.2.2 (active)
gorename, v1.1.0 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.43.0 (active)
language-clojure, v0.22.0 (active)
language-crystal-actual, v0.33.0 (active)
language-cypher, v0.3.0 (active)
language-docker, v1.1.7 (active)
language-elixir, v0.16.0 (active)
language-fish-shell, v1.0.5 (active)
language-glsl, v2.0.1 (active)
language-graphql, v0.2.0 (active)
language-haml, v0.24.0 (active)
language-haskell, v1.9.9 (active)
language-hlsl, v1.2.0 (active)
language-lex-flex, v0.1.0 (active)
language-lua, v0.9.11 (active)
language-nginx, v0.6.2 (active)
language-rspec, v0.5.0 (active)
language-rust, v0.4.7 (active)
language-slim, v0.5.0 (active)
linter, v1.11.18 (active)
linter-coffeelint, v1.1.2 (active)
linter-jshint, v3.0.0 (active)
linter-lua, v1.0.2 (active)
linter-rubocop, v0.5.0 (inactive)
navigator-go, v1.1.3 (active)
pigments, v0.37.0 (active)
pretty-json, v1.6.0 (active)
ruby-block, v0.3.5 (active)
set-syntax, v0.3.2 (active)
symbol-gen, v1.3.1 (active)
tabs-to-spaces, v1.0.2 (active)
tasks, v2.6.3 (active)
tester-go, v2.0.2 (active)
todo-show, v1.7.0 (inactive)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.22.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by nirix** [comment]
I ran into this issue myself last night and v1.1.2 has been released that fixes the issue.
