### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by xlaywan** [nirix/atom-editor-settings#3]
![image](https://cloud.githubusercontent.com/assets/9087446/5527112/8276f668-8a14-11e4-8962-0ecdc390e2fe.png)
![image](https://cloud.githubusercontent.com/assets/9087446/5527164/0d989260-8a15-11e4-8111-57cddb15be50.png)

Another packages installing properly.

**Comment by Code-Vortex** [comment]
I cannot install this package too

```
Installing “editor-settings@0.4.0” failed.Hide output…

> runas@1.1.0 install /tmp/apm-install-dir-115023-3482-8ysj5m/node_modules/editor-settings/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-115023-3482-8ysj5m/node_modules/editor-settings/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:88: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-115023-3482-8ysj5m/node_modules/editor-settings/node_modules/pathwatcher/node_modules/runas/build'

npm http GET https://registry.npmjs.org/season
npm http GET https://registry.npmjs.org/cson-safe
npm http GET https://registry.npmjs.org/pathwatcher
npm http 304 https://registry.npmjs.org/cson-safe
npm http 304 https://registry.npmjs.org/pathwatcher
npm http 304 https://registry.npmjs.org/season
npm http GET https://registry.npmjs.org/coffee-script-redux/2.0.0-beta8
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/nan/1.2.0
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/runas
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/coffee-script-redux/2.0.0-beta8
npm http GET https://registry.npmjs.org/StringScanner
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/esmangle
npm http GET https://registry.npmjs.org/source-map/0.1.11
npm http GET https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/runas
npm http 304 https://registry.npmjs.org/nan/1.2.0
npm http 304 https://registry.npmjs.org/esmangle
make: g++: Command not found
make: *** [Release/obj.target/runas/src/main.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.17.8-300.fc21.x86_64
gyp ERR! command "node" "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115023-3482-8ysj5m/node_modules/editor-settings/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/StringScanner
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/source-map/0.1.11
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/estraverse
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/escope
npm http GET https://registry.npmjs.org/estraverse
npm http GET https://registry.npmjs.org/esshorten
npm ERR! runas@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@1.1.0 install script.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.17.8-300.fc21.x86_64
npm ERR! command "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/bin/node" "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/local/share/atom/resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/sasa/.atom/.apmrc" "install" "/home/sasa/.atom/.node-gyp/.atom/.apm/editor-settings/0.4.0/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! cwd /tmp/apm-install-dir-115023-3482-8ysj5m
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/escope
npm http 304 https://registry.npmjs.org/esshorten
npm http 304 https://registry.npmjs.org/estraverse
npm http 304 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/estraverse
npm WARN optional dep failed, continuing escodegen@0.0.28
npm http 304 https://registry.npmjs.org/minimist
npm WARN optional dep failed, continuing esmangle@0.0.17
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/apm-install-dir-115023-3482-8ysj5m/npm-debug.log
npm ERR! not ok code 0
```

> My OS is fedora 21 , using Atom `0.174.0`

**Comment by JPTigr** [comment]
I have a similar issue. See below.

![image](https://cloud.githubusercontent.com/assets/8000673/7133426/444274e2-e28b-11e4-8e5b-91a613a92aea.png)

**Comment by nirix** [comment]
This is an issue with the `runas` package that is being used by `pathwatcher`, used to watch for configuration file changes.

I'm currently looking at alternatives to use, such as the [`fs.watch()`](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener).

**Comment by nirix** [comment]
Version `1.0.3` should now be installable on Windows. Tested on Windows 7.
