### ISSUE TITLE
Failed to load the editor-settings package

### ISSUE THREAD

**Issue by joshourisman** [nirix/atom-editor-settings#6]
[Enter steps to reproduce below:]

1. Open Atom.app.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [editor-settings](https://github.com/nirix/atom-editor-settings) package, v0.4.0

### Stack Trace

Failed to load the editor-settings package

```
At Module version mismatch. Expected 41, got 16.

Error: Module version mismatch. Expected 41, got 16.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/josho/.atom/packages/editor-settings/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/josho/.atom/packages/editor-settings/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:475:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".DS_Stor",
      "migrations"
    ],
    "disabledPackages": [
      "background-tips",
      "deprecation-cop",
      "autocomplete"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.0
atom-handlebars, v0.4.0
auto-detect-indentation, v0.3.0
autoclose-html, v0.15.0
autocomplete-plus, v2.4.2
django-templates, v0.3.0
editor-settings, v0.4.0
language-cjsx, v0.2.0
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-flake8, v1.3.0
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
monokai-seti, v0.4.0
react, v0.9.11
resize-indent, v0.2.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by nogorilla** [comment]
+1

**Comment by juanstiza** [comment]
+1

**Comment by nirix** [comment]
I've updated the dependencies and fixed the setting the editor options, but things such as the font size, family, indent guide and line height are not currently working.

**Comment by nogorilla** [comment]
Looks like it's back

1. Start Atom

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [editor-settings](https://github.com/nirix/atom-editor-settings) package, v0.5.0

### Stack Trace

Failed to load the editor-settings package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gabe/.atom/packages/editor-settings/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/gabe/.atom/packages/editor-settings/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gabe/.atom/packages/editor-settings/lib/editor-settings.coffee:4:10)
  at Object.<anonymous> (/Users/gabe/.atom/packages/editor-settings/lib/editor-settings.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:619:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:52:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".idea"
    ],
    "projectHome": "/Users/gabriel.smith/workspace",
    "audioBeep": false,
    "themes": [
      "beacon-ui",
      "base16-eighties-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-angularjs, v0.1.2
atom-jshint, v1.5.0
autoclose-html, v0.15.0
autocomplete-plus, v2.6.0
base16-eighties-dark-syntax, v0.1.0
beacon-ui, v0.5.0
docblockr, v0.6.3
editor-settings, v0.5.0
emmet, v2.3.4
file-icons, v1.5.2
grunt-runner, v0.8.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
ionic-atom, v0.3.1
language-apache, v1.2.0
language-blade, v0.12.0
language-ini, v1.9.0
language-jade, v0.3.0
language-twig, v1.5.2
laravel, v0.4.2
linter, v0.12.0
linter-ruby, v0.1.4
minimap, v4.6.0
php-twig, v3.0.0
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by nirix** [comment]
I updated pathwatcher and ran `apm rebuild` in the directory which appears to have fix it.
